"""empty message

Revision ID: 72f6c578352f
Revises: adb717c69f55
Create Date: 2017-09-12 21:12:12.541095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72f6c578352f'
down_revision = 'adb717c69f55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Marker',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start', sa.DateTime(), nullable=True),
    sa.Column('stop', sa.DateTime(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'sensor', sa.Column('offset', sa.Integer(), nullable=True))
    op.add_column(u'sensor', sa.Column('scale', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'sensor', 'scale')
    op.drop_column(u'sensor', 'offset')
    op.drop_table('Marker')
    # ### end Alembic commands ###
