"""empty message

Revision ID: adb717c69f55
Revises: 0c53b7dd8fc5
Create Date: 2017-08-02 17:19:40.822131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'adb717c69f55'
down_revision = '0c53b7dd8fc5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('node', sa.Column('last_update', sa.DateTime(), nullable=True))
    op.add_column('node', sa.Column('name', sa.Integer(), nullable=True))
    op.add_column('sensor', sa.Column('last_update', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sensor', 'last_update')
    op.drop_column('node', 'name')
    op.drop_column('node', 'last_update')
    # ### end Alembic commands ###
