"""empty message

Revision ID: d84d263de64c
Revises: 72f6c578352f
Create Date: 2017-09-13 13:56:07.185452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd84d263de64c'
down_revision = '72f6c578352f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('sensor__value_index', 'sensorValue', [sa.text(u'timestamp DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('sensor__value_index', table_name='sensorValue')
    # ### end Alembic commands ###
